### ISSUE TITLE
Error: Cannot find module './structures/cacheCollection.js

### ISSUE THREAD

**Issue by abewartech** [ArDevy/contapi#1]
Thanks for making this package

I run this package and show this error
Error: Cannot find module './structures/cacheCollection.js

Any idea to resolve this?

**Comment by ArDevy** [comment]
May be a little late to your response as my emails are very packed. I will look into it real quickly, apologies

**Comment by ArDevy** [comment]
Found an incorrectly imported file as described in the error you received. I currently locked out of my npm account so give me a bit to get back in

**Comment by ArDevy** [comment]
Found an incorrectly imported file as described in the error you received. I just put out an update to get the issue fixed, should be working now. Apologies for the issue. Let me know if you continue to experience the problem!
