### ISSUE TITLE
Wrong password/login will hang the process forever?

### ISSUE THREAD

**Issue by cpainchaud** [ArDevy/contapi#3]
Hi,

 I am struggling with error checking at login time because you emit 'ready' but never emit 'error' or so at login time, resulting in my script to wait forever for 'ready' signal which never happens ofc ...

**Comment by ArDevy** [comment]
Apologies, I hadn't thought about adding this. I am currently working into merging your pull request! Thank you for the help, and as well thank you for reporting this issue. I apologize for not responding earlier, github notifications are off

**Comment by ArDevy** [comment]
I have now published the update to NPM, thank you once again!
